FROM node:20-alpine as frontend-builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY App.tsx index.html index.tsx metadata.json tsconfig.json types.ts vite.config.ts ./
COPY components ./components
COPY services ./services
RUN npm run build

FROM nginx:alpine
COPY --from=frontend-builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf